  insert into RSV_SIS_KBN
  ( RSK_SID, RSK_NAME, RSK_SORT, RSK_AUID, RSK_ADATE, RSK_EUID, RSK_EDATE) 
  values 
  ( 1, '部屋', 1, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP);

  insert into RSV_SIS_KBN
  ( RSK_SID, RSK_NAME, RSK_SORT, RSK_AUID, RSK_ADATE, RSK_EUID, RSK_EDATE) 
  values 
  ( 2, '物品', 2, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP);

  insert into RSV_SIS_KBN
  ( RSK_SID, RSK_NAME, RSK_SORT, RSK_AUID, RSK_ADATE, RSK_EUID, RSK_EDATE) 
  values 
  ( 3, '車', 3, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP);

  insert into RSV_SIS_KBN
  ( RSK_SID, RSK_NAME, RSK_SORT, RSK_AUID, RSK_ADATE, RSK_EUID, RSK_EDATE) 
  values 
  ( 4, '書籍', 4, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP);

  insert into RSV_SIS_KBN
  ( RSK_SID, RSK_NAME, RSK_SORT, RSK_AUID, RSK_ADATE, RSK_EUID, RSK_EDATE) 
  values 
  ( 5, 'その他', 5, 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP);