  insert into WML_ADM_CONF
  ( WAD_ACNT_MAKE, WAD_ACCT_SENDFORMAT, WAD_ACCT_LOG_REGIST, WAD_PERMIT_KBN, WAD_AUTO_RECEIVE_TIME, WAD_DISK, WAD_DISK_SIZE, WAD_DELRECEIVE, WAD_AUTORECEIVE, WAD_CHECK_ADDRESS, WAD_CHECK_FILE, WAD_COMPRESS_FILE, WAD_TIMESENT, WAD_SEND_LIMIT, WAD_SEND_LIMIT_SIZE, WAD_FWLIMIT, WAD_BCC, WAD_BCC_TH, WAD_WARN_DISK, WAD_WARN_DISK_TH, WAD_SETTING_SERVER, WAD_PROXY_USER, WAD_COMPRESS_FILE_DEF, WAD_TIMESENT_DEF
   )
  values
  ( 1, 0, 1, 1, 5, 0, null, 0, 1, 0, 0, 2, 2, 0, null, 0, 0, null, 0, null, 1, 1, 1, 2);