create table ADR_ADDRESS
(
  ADR_SID          integer           not null,
  ADR_SEI          varchar(30)       not null,
  ADR_MEI          varchar(30)       not null,
  ADR_SEI_KN       varchar(60)       not null,
  ADR_MEI_KN       varchar(60)       not null,
  ADR_SINI         varchar(3)        not null,
  ACO_SID          integer,
  ABA_SID          integer,
  ADR_SYOZOKU      varchar(60),
  APS_SID          integer,
  ADR_MAIL1        varchar(50),
  ADR_MAIL_CMT1    varchar(10),
  ADR_MAIL2        varchar(50),
  ADR_MAIL_CMT2    varchar(10),
  ADR_MAIL3        varchar(50),
  ADR_MAIL_CMT3    varchar(10),
  ADR_POSTNO1      varchar(3),
  ADR_POSTNO2      varchar(4),
  TDF_SID          integer,
  ADR_ADDR1        varchar(100),
  ADR_ADDR2        varchar(100),
  ADR_TEL1         varchar(20),
  ADR_TEL_NAI1     varchar(10),
  ADR_TEL_CMT1     varchar(10),
  ADR_TEL2         varchar(20),
  ADR_TEL_NAI2     varchar(10),
  ADR_TEL_CMT2     varchar(10),
  ADR_TEL3         varchar(20),
  ADR_TEL_NAI3     varchar(10),
  ADR_TEL_CMT3     varchar(10),
  ADR_FAX1         varchar(20),
  ADR_FAX_CMT1     varchar(10),
  ADR_FAX2         varchar(20),
  ADR_FAX_CMT2     varchar(10),
  ADR_FAX3         varchar(20),
  ADR_FAX_CMT3     varchar(10),
  ADR_BIKO         varchar(1000),
  ADR_PERMIT_VIEW  integer,
  ADR_PERMIT_EDIT  integer,
  ADR_AUID         integer           not null,
  ADR_ADATE        timestamp        not null,
  ADR_EUID         integer           not null,
  ADR_EDATE        timestamp        not null,
  primary key (ADR_SID)
);