create table WML_ADM_CONF
(
  WAD_ACNT_MAKE         integer      not null,
  WAD_ACCT_SENDFORMAT   integer      not null,
  WAD_ACCT_LOG_REGIST   integer      not null,
  WAD_PERMIT_KBN        integer      not null,
  WAD_AUTO_RECEIVE_TIME integer      not null,
  WAD_DISK              integer      not null,
  WAD_DISK_SIZE         integer,
  WAD_DISK_COMP         integer      default 0,
  WAD_DELRECEIVE        integer      not null,
  WAD_AUTORECEIVE       integer      not null,
  WAD_SEND_HOST         varchar(100),
  WAD_SEND_PORT         integer      default 25,
  WAD_SEND_SSL          integer      default 0,
  WAD_RECEIVE_HOST      varchar(100),
  WAD_RECEIVE_PORT      integer      default 110,
  WAD_RECEIVE_SSL       integer      default 0,
  WAD_CHECK_ADDRESS     integer      not null,
  WAD_CHECK_FILE        integer      not null,
  WAD_COMPRESS_FILE     integer      not null,
  WAD_TIMESENT          integer      not null,
  WAD_SEND_LIMIT        integer      not null,
  WAD_SEND_LIMIT_SIZE   integer,
  WAD_FWLIMIT           integer      not null,
  WAD_BCC               integer      not null,
  WAD_BCC_TH            integer,
  WAD_WARN_DISK         integer      not null,
  WAD_WARN_DISK_TH      integer,
  WAD_SETTING_SERVER    integer      not null,
  WAD_PROXY_USER        integer      not null,
  WAD_COMPRESS_FILE_DEF integer,
  WAD_TIMESENT_DEF      integer
);
