create table NTP_EXTENED
(
      NEX_SID               integer           not null,
      NEX_KBN               integer           not null,
      NEX_DWEEK1            integer                   ,
      NEX_DWEEK2            integer                   ,
      NEX_DWEEK3            integer                   ,
      NEX_DWEEK4            integer                   ,
      NEX_DWEEK5            integer                   ,
      NEX_DWEEK6            integer                   ,
      NEX_DWEEK7            integer                   ,
      NEX_DAY               integer                   ,
      NEX_WEEK              integer                   ,
      NEX_TIME_FR            timestamp         not null,
      NEX_TIME_TO            timestamp         not null,
      NEX_KADO_HH           integer           not null,
      NEX_KADO_MM           integer           not null,
      NEX_TRAN_KBN          integer           not null,
      NEX_DATE_FR           timestamp         not null,
      NEX_DATE_TO           timestamp         not null,
      NEX_MGY_SID           integer           not null,
      NEX_NAN_SID           integer           not null,
      NEX_ACO_SID           integer                   ,
      NEX_ABO_SID           integer                   ,
      NEX_TITLE             varchar(50)       not null,
      NEX_TITLE_CLO         integer                   ,
      NEX_MPR_SID           integer           not null,
      NEX_MKB_SID           integer           not null,
      NEX_MKH_SID           integer           not null,
      NEX_TIEUP_SID         integer                   ,
      NEX_KEIZOKU           integer           not null,
      NEX_ACTEND            timestamp                 ,
      NEX_DETAIL            varchar(1000)     not null,
      NEX_ASSIGN            varchar(1000)             ,
      NEX_KINGAKU           integer                   ,
      NEX_MIKOMI            integer                   ,
      NEX_SYOKAN            varchar(1000)             ,
      NEX_PUBLIC            integer                   ,
      NEX_EDIT              integer                   ,
      NEX_AUID              integer                   ,
      NEX_ADATE             timestamp         not null,
      NEX_EUID              integer                   ,
      NEX_EDATE             timestamp         not null,
      primary key (NEX_SID)
);
