create table SCH_PRI_CONF
(
        USR_SID           integer         not null,
        SCC_FR_DATE       timestamp       not null,
        SCC_TO_DATE       timestamp       not null,
        SCC_DSP_GROUP     integer         not null,
        SCC_SORT_KEY1     integer         not null,
        SCC_SORT_ORDER1   integer         not null,
        SCC_SORT_KEY2     integer         not null,
        SCC_SORT_ORDER2   integer         not null,
        SCC_INI_FR_DATE   timestamp       not null,
        SCC_INI_TO_DATE   timestamp       not null,
        SCC_INI_PUBLIC    integer         not null,
        SCC_INI_FCOLOR    integer         not null,
        SCC_INI_EDIT      integer         not null,
        SCC_DSP_LIST      integer         not null,
        SCC_DSP_MYGROUP   integer         ,
        SCC_SMAIL         integer         not null,
        SCC_SMAIL_GROUP   integer         not null,
        SCC_RELOAD        integer         not null,
        SCC_INI_WEEK      integer         not null,
        SCC_SORT_EDIT     integer         not null,
        SCC_DEF_DSP       integer         not null,
        SCC_REPEAT_KBN    integer         not null,
        SCC_REPEAT_MY_KBN integer         not null,
        SCC_GRP_SHOW_KBN  integer         not null,
        SCC_AUID          integer         not null,
        SCC_ADATE         timestamp       not null,
        SCC_EUID          integer         not null,
        SCC_EDATE         timestamp       not null,
        SCC_SMAIL_ATTEND         integer         not null,
        SCC_INI_SAME         integer         not null,
        primary key (USR_SID)
);