create table SCH_DATA
(
        SCD_SID         integer         not null,
        SCD_USR_SID     integer         not null,
        SCD_GRP_SID     integer                 ,
        SCD_USR_KBN     integer                 ,
        SCD_FR_DATE     timestamp               ,
        SCD_TO_DATE     timestamp               ,
        SCD_DAILY       integer                 ,
        SCD_BGCOLOR     integer                 ,
        SCD_TITLE       varchar(50)             ,
        SCD_VALUE       varchar(1000)           ,
        SCD_BIKO        varchar(1000)           ,
        SCD_PUBLIC      integer                 ,
        SCD_AUID        integer         not null,
        SCD_ADATE       timestamp       not null,
        SCD_EUID        integer         not null,
        SCD_EDATE       timestamp       not null,
        SCE_SID         integer                 ,
        SCD_RSSID       integer                 ,
        SCD_EDIT        integer                 ,
        SCD_ATTEND_KBN        integer                 ,
        SCD_ATTEND_ANS        integer                 ,
        SCD_ATTEND_AU_KBN        integer                 ,
        primary key (SCD_SID)
);