create table SCH_ADM_CONF
(
        SAD_CRANGE         integer    not null,
        SAD_ATDEL_FLG      integer    not null,
        SAD_ATDEL_Y        integer            ,
        SAD_ATDEL_M        integer            ,
        SAD_HOUR_DIV       integer            ,
        SAD_SORT_KBN       integer    not null,
        SAD_SORT_KEY1      integer    not null,
        SAD_SORT_ORDER1    integer    not null,
        SAD_SORT_KEY2      integer    not null,
        SAD_SORT_ORDER2    integer    not null,
        SAD_INI_EDIT_STYPE integer    not null,
        SAD_INI_EDIT       integer    not null,
        SAD_REPEAT_STYPE   integer    not null,
        SAD_REPEAT_KBN     integer    not null,
        SAD_REPEAT_MY_KBN  integer    not null,
        SAD_AUID           integer    not null,
        SAD_ADATE          timestamp  not null,
        SAD_EUID           integer    not null,
        SAD_EDATE          timestamp  not null,
        SAD_DSP_GROUP      integer    not null,
        SAD_MSG_COLOR_KBN  integer    not null,
        SAD_SMAIL_SEND_KBN integer    not null,
        SAD_SMAIL          integer    not null,
        SAD_SMAIL_GROUP    integer    not null,
        SAD_SMAIL_ATTEND    integer    not null,
        SAD_INI_PUBLIC    integer    not null,
        SAD_PUBLIC_KBN    integer    not null,
        SAD_INI_SAME_STYPE    integer not    null,
        SAD_INI_SAME    integer    not null
) ;