create table SCH_EXDATA
(
    SCE_SID        integer         not null,
    SCE_KBN        integer         not null,
    SCE_DWEEK1     integer                 ,
    SCE_DWEEK2     integer                 ,
    SCE_DWEEK3     integer                 ,
    SCE_DWEEK4     integer                 ,
    SCE_DWEEK5     integer                 ,
    SCE_DWEEK6     integer                 ,
    SCE_DWEEK7     integer                 ,
    SCE_DAY        integer                 ,
    SCE_WEEK       integer                 ,
    SCE_MONTH_YEARLY integer                 ,
    SCE_DAY_YEARLY integer                 ,
    SCE_TIME_FR    timestamp       not null,
    SCE_TIME_TO    timestamp       not null,
    SCE_TRAN_KBN   integer         not null,
    SCE_DATE_FR    timestamp       not null,
    SCE_DATE_TO    timestamp       not null,
    SCE_BGCOLOR    integer         not null,
    SCE_TITLE      varchar(50)             ,
    SCE_VALUE      varchar(1000)           ,
    SCE_BIKO       varchar(1000)           ,
    SCE_PUBLIC     integer                 ,
    SCE_EDIT       integer                 ,
    SCE_DAILY      integer                 ,
    SCE_AUID       integer         not null,
    SCE_ADATE      timestamp       not null,
    SCE_EUID       integer         not null,
    SCE_EDATE      timestamp       not null,
    primary key (SCE_SID)
);