create table BBS_FOR_INF
(
        BFI_SID            integer not null,
        BFI_NAME           varchar(150) not null,
        BFI_CMT            varchar(3000) not null,
        BFI_SORT           integer not null,
        BFI_REPLY          integer not null,
        BFI_READ           integer not null,
        BIN_SID            bigint  not null,
        BFI_MREAD          integer not null,
        BFI_TEMPLATE_KBN   integer not null,
        BFI_TEMPLATE       varchar(2000),
        BFI_TEMPLATE_WRITE integer not null,
        BFI_AUID           integer not null,
        BFI_ADATE          timestamp not null,
        BFI_EUID           integer not null,
        BFI_EDATE          timestamp not null,
        BFI_DISK           integer not null,
        BFI_DISK_SIZE      integer,
        BFI_WARN_DISK      integer not null,
        BFI_WARN_DISK_TH   integer,
        BFI_LIMIT           integer not null,
        BFI_LIMIT_DATE           integer,
        BFI_KEEP           integer not null,
        BFI_KEEP_DATE_Y           integer,
        BFI_KEEP_DATE_M           integer,
        BFI_LIMIT_ON           integer not null,
        primary key (BFI_SID)
) ;