  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 1, '北海道', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 2, '青森', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 3, '岩手', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 4, '宮城', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 5, '秋田', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 6, '山形', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 7, '福島', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 8, '東京', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 9, '神奈川', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 10, '埼玉', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 11, '千葉', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 12, '茨城', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 13, '栃木', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 14, '群馬', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 15, '山梨', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 16, '新潟', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 17, '長野', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 18, '富山', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 19, '石川', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 20, '福井', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 21, '愛知', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 22, '岐阜', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 23, '静岡', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 24, '三重', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 25, '大阪', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 26, '兵庫', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 27, '京都', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 28, '滋賀', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 29, '奈良', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 30, '和歌山', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 31, '鳥取', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 32, '島根', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 33, '岡山', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 34, '広島', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 35, '山口', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 36, '徳島', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 37, '香川', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 38, '愛媛', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 39, '高知', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 40, '福岡', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 41, '佐賀', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 42, '長崎', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 43, '熊本', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 44, '大分', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 45, '宮崎', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 46, '鹿児島', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  insert into CMN_TDFK
  ( TDF_SID, TDF_NAME, TDF_AUID, TDF_ADATE, TDF_EUID, TDF_EDATE ) 
  values 
  ( 47, '沖縄', 0, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP  );
  