delete from CMN_HOLIDAY_TEMPLATE
;
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    0
    ,1
    ,1
    ,'年末年始休暇  '
    ,0
    ,0
    ,0
    ,1
    ,0
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    1
    ,1
    ,2
    ,'年末年始休暇 '
    ,0
    ,0
    ,0
    ,1
    ,0
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    2
    ,1
    ,3
    ,'年末年始休暇 '
    ,0
    ,0
    ,0
    ,1
    ,0
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    3
    ,0
    ,0
    ,'成人の日 '
    ,1
    ,2
    ,1
    ,1
    ,1
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    4
    ,2
    ,11
    ,'建国記念日 '
    ,0
    ,0
    ,0
    ,0
    ,0
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    5
    ,3
    ,20
    ,'春分の日 '
    ,0
    ,0
    ,0
    ,0
    ,0
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    6
    ,4
    ,29
    ,'昭和の日 '
    ,0
    ,0
    ,0
    ,0
    ,0
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    7
    ,5
    ,3
    ,'憲法記念日 '
    ,0
    ,0
    ,0
    ,0
    ,0
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    8
    ,5
    ,4
    ,'みどりの日 '
    ,0
    ,0
    ,0
    ,0
    ,0
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    9
    ,5
    ,5
    ,'こどもの日 '
    ,0
    ,0
    ,0
    ,0
    ,0
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    10
    ,0
    ,0
    ,'海の日 '
    ,7
    ,3
    ,1
    ,0
    ,1
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    11
    ,0
    ,0
    ,'敬老の日 '
    ,9
    ,3
    ,1
    ,0
    ,1
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    12
    ,9
    ,23
    ,'秋分の日 '
    ,0
    ,0
    ,0
    ,0
    ,0
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    13
    ,0
    ,0
    ,'体育の日 '
    ,10
    ,2
    ,1
    ,0
    ,1
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    14
    ,11
    ,3
    ,'文化の日 '
    ,0
    ,0
    ,0
    ,0
    ,0
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    15
    ,11
    ,23
    ,'勤労感謝の日 '
    ,0
    ,0
    ,0
    ,0
    ,0
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    16
    ,12
    ,23
    ,'天皇誕生日 '
    ,0
    ,0
    ,0
    ,0
    ,0
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    17
    ,12
    ,29
    ,'年末年始休暇 '
    ,0
    ,0
    ,0
    ,1
    ,0
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    18
    ,12
    ,30
    ,'年末年始休暇 '
    ,0
    ,0
    ,0
    ,1
    ,0
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );
  insert
  into
    CMN_HOLIDAY_TEMPLATE (
      HLT_SID
      ,HLT_DATE_MONTH
      ,HLT_DATE_DAY
      ,HLT_NAME
      ,HLT_EX_MONTH
      ,HLT_EX_WEEK_MONTH
      ,HLT_EX_DAY_WEEK
      ,HLT_EX_FURIKAE
      ,HLT_EXFLG
      ,HLT_ADUSER
      ,HLT_ADDATE
      ,HLT_UPUSER
      ,HLT_UPDATE
    )
  values (
    19
    ,12
    ,31
    ,'年末年始休暇'
    ,0
    ,0
    ,0
    ,1
    ,0
    ,0
    ,current_timestamp
    ,0
    ,current_timestamp
  );

 insert
 into CMN_SAIBAN(SBN_SID, SBN_SID_SUB, SBN_NUMBER, SBN_STRING, SBN_AID, SBN_ADATE, SBN_EID, SBN_EDATE)
           values ('main', 'hlt', 19, 'hlt', 0, current_timestamp, 0, current_timestamp);
