create table RSV_SIS_DATA
(
  RSG_SID       integer not null,
  RSD_SID       integer not null,
  RSD_ID        varchar(15) not null,
  RSD_NAME      varchar(100) not null,
  RSD_SNUM      varchar(20),
  RSD_PROP_1    varchar(10),
  RSD_PROP_2    varchar(1),
  RSD_PROP_3    varchar(1),
  RSD_PROP_4    varchar(100),
  RSD_PROP_5    varchar(100),
  RSD_PROP_6    varchar(100),
  RSD_PROP_7    varchar(100),
  RSD_PROP_8    varchar(100),
  RSD_PROP_9    varchar(100),
  RSD_PROP_10   varchar(100),
  RSD_BIKO      varchar(1000),
  RSD_PLA_CMT   varchar(50),
  RSD_SORT      integer not null,
  RSD_IMG_CMT1  varchar(50),
  RSD_IMG_CMT2  varchar(50),
  RSD_IMG_CMT3  varchar(50),
  RSD_IMG_CMT4  varchar(50),
  RSD_IMG_CMT5  varchar(50),
  RSD_IMG_CMT6  varchar(50),
  RSD_IMG_CMT7  varchar(50),
  RSD_IMG_CMT8  varchar(50),
  RSD_IMG_CMT9  varchar(50),
  RSD_IMG_CMT10 varchar(50),
  RSD_ID_DF       integer not null,
  RSD_SNUM_DF     integer not null,
  RSD_PROP_1_DF   integer not null default 1,
  RSD_PROP_2_DF   integer not null default 1,
  RSD_PROP_3_DF   integer not null default 1,
  RSD_PROP_4_DF   integer not null default 1,
  RSD_PROP_5_DF   integer not null default 1,
  RSD_PROP_6_DF   integer not null default 1,
  RSD_PROP_7_DF   integer not null default 1,
  RSD_PROP_8_DF   integer not null default 1,
  RSD_PROP_9_DF   integer not null default 1,
  RSD_PROP_10_DF  integer not null default 1,
  RSD_IMG_CMT1_DF  integer not null default 1,
  RSD_IMG_CMT2_DF  integer not null default 1,
  RSD_IMG_CMT3_DF  integer not null default 1,
  RSD_IMG_CMT4_DF  integer not null default 1,
  RSD_IMG_CMT5_DF  integer not null default 1,
  RSD_IMG_CMT6_DF  integer not null default 1,
  RSD_IMG_CMT7_DF  integer not null default 1,
  RSD_IMG_CMT8_DF  integer not null default 1,
  RSD_IMG_CMT9_DF  integer not null default 1,
  RSD_IMG_CMT10_DF integer not null default 1,
  RSD_BIKO_DF      integer not null default 1,
  RSD_IMG_DF       integer not null default 1,
  RSD_PLA_CMT_DF   integer not null default 1,
  RSD_APPR_KBN     integer not null default 0,
  RSD_APPR_KBN_DF  integer not null default 1,
  RSD_AUID      integer not null,
  RSD_ADATE     timestamp not null,
  RSD_EUID      integer not null,
  RSD_EDATE     timestamp not null,
  primary key 	(RSD_SID)
);