create table RSV_SIS_RYRK
(
  RSR_RSID      integer not null,
  RSR_KBN       integer not null,
  RSR_DWEEK1    integer,
  RSR_DWEEK2    integer,
  RSR_DWEEK3    integer,
  RSR_DWEEK4    integer,
  RSR_DWEEK5    integer,
  RSR_DWEEK6    integer,
  RSR_DWEEK7    integer,
  RSR_DAY       integer,
  RSR_WEEK      integer,
  RSR_MONTH_YEARLY integer,
  RSR_DAY_YEARLY integer,
  RSR_TIME_FR   timestamp not null,
  RSR_TIME_TO   timestamp not null,
  RSR_TRAN_KBN  integer not null,
  RSR_DATE_FR   timestamp not null,
  RSR_DATE_TO   timestamp not null,
  RSR_MOK       varchar(50) not null,
  RSR_BIKO      varchar(1000),
  RSR_EDIT      integer,
  RSR_AUID      integer not null,
  RSR_ADATE     timestamp not null,
  RSR_EUID      integer not null,
  RSR_EDATE     timestamp not null,
  primary key 	(RSR_RSID)
);